#!/usr/bin/env node
/**
 * Ping IndexNow with every URL in public/sitemap.xml.
 *
 * IndexNow is a push protocol: one request tells Bing, Yandex, Seznam and Naver
 * that these URLs changed, instead of waiting for a crawl. Google does not
 * participate, and neither does Brave — those still come from Search Console
 * and Brave's submit-url form. Bing matters here beyond Bing itself, because
 * several AI answer engines read from the Bing index.
 *
 * The key file at public/<key>.txt must be live on the domain before this
 * works — IndexNow fetches it to prove you own the host. So: deploy first,
 * then run `npm run indexnow`.
 */
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const PUBLIC_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "public");
const HOST = "legacyfalcons.com";

// Generated by Bing Webmaster Tools rather than by us, so submissions show up
// under the BWT account. Changing it means replacing public/<key>.txt to match.
const KEY = "fa3a422f068b4a33a6a74bc72a7cc406";

async function checkKeyFile() {
  const contents = (await readFile(join(PUBLIC_DIR, `${KEY}.txt`), "utf8")).trim();
  if (contents !== KEY) {
    throw new Error(`public/${KEY}.txt must contain exactly "${KEY}", got "${contents}"`);
  }
}

async function sitemapUrls() {
  const xml = await readFile(join(PUBLIC_DIR, "sitemap.xml"), "utf8");
  return [...xml.matchAll(/<loc>\s*([^<\s]+)\s*<\/loc>/g)]
    .map((m) => m[1])
    .filter((u) => u.startsWith(`https://${HOST}/`) || u === `https://${HOST}`);
}

await checkKeyFile();
const urlList = await sitemapUrls();
if (!urlList.length) throw new Error("sitemap.xml yielded no URLs");

// Confirm the key file is actually reachable, so a 403 later is not a mystery.
// A plain status check is not enough: vercel.json rewrites every unmatched path
// to index.html, so a not-yet-deployed key file still answers 200 with the SPA.
const probe = await fetch(`https://${HOST}/${KEY}.txt`);
const probeBody = probe.ok ? (await probe.text()).trim() : "";
if (probeBody !== KEY) {
  throw new Error(
    `Key file not live yet: https://${HOST}/${KEY}.txt returned ${probe.status} ` +
      `and did not contain the key. Deploy first, then re-run.`
  );
}

const res = await fetch("https://api.indexnow.org/IndexNow", {
  method: "POST",
  headers: { "Content-Type": "application/json; charset=utf-8" },
  body: JSON.stringify({ host: HOST, key: KEY, keyLocation: `https://${HOST}/${KEY}.txt`, urlList }),
});

// 200 = accepted, 202 = accepted but key still being validated. Both are fine.
const body = await res.text();
console.log(`IndexNow ${res.status} ${res.statusText}${body ? ` — ${body}` : ""}`);
for (const u of urlList) console.log(`  submitted ${u}`);
if (res.status !== 200 && res.status !== 202) process.exit(1);
